authentication:
    api_key: 'API_KEY'
    api_secret_key: 'API_SECRET_KEY'

    

# compute:
#     management_server:
#         user_on_management: root
#         userhome_on_management: /root
#         instance:
#             use_existing: false
#             name: cloudify-management-server
#             image: 299fd26a-2b4f-4ff4-acfd-23d2682d65ba
#             size: Medium
#         management_keypair:
#             use_existing: true
#             name: cloudify-management-kp
# #            provided:
# #                public_key_filepath:
# #                private_key_filepath: ~/.ssh/cloudify-management-kp.pem
#             auto_generated:
#                 private_key_target_path: ~/.ssh/cloudify-management-kp.pem
#     agent_servers:
#         agents_keypair:
#             use_existing: true
#             name: cloudify-agents-kp
# #            provided:
# #                public_key_filepath:
# #                private_key_filepath: ~/.ssh/cloudify-agents-kp.pem
#             auto_generated:
#                 private_key_target_path: ~/.ssh/cloudify-agents-kp.pem


# networking:
#     agents_security_group:
#         use_existing: true
#         name: cloudify-agents-sg
#         protocol: TCP
#         cidr: 0.0.0.0/0
#         ports: [22, 27017, 28017, 8080]
#     management_security_group:
#         use_existing: true
#         name: cloudify-management-sg
#         protocol: TCP
#         cidr: 0.0.0.0/0
#         ports: [5555, 5672, 53229, 22, 8100, 80]

# cloudify_components_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/3.0.0/nightly_1/cloudify-components_3.0.0-beta-b1_amd64.deb
    # cloudify_core_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/3.0.0/nightly_1/cloudify-core_3.0.0-beta-b1_amd64.deb
    # cloudify_ui_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/3.0.0/nightly_1/cloudify-ui_3.0.0-beta-b1_amd64.deb
    # cloudify_ubuntu_agent_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/3.0.0/nightly_1/ubuntu-agent_3.0.0-beta-b1_amd64.deb
